directories:
  - /path/to/directory1
  - /path/to/directory2
  - s3://bucket/path/to/folder1
  - s3://bucket/path/to/folder2
file_size_threshold: 100  # X, the file size in units
units: MB  # U, the units to be used (MB, GB, TB)
